### ISSUE TITLE
Color input() not working

### ISSUE THREAD

**Issue by LarryBarker** [samuelayo/terminal-chat#1]
On windows, any input() statement that is supposed to be colored does not work. This seems to be a problem with Python 3. Are there any work arounds?

Also, I had to use colorama to get the print() statements to work properly on windows with anaconda.

**Comment by samuelayo** [comment]
Hi there, sorry for the late response. I do not think it has to do with python3, but windows itself. I believe the package termcolor does not support windows, or it is hard to color outputs in windows. 

About the print statements, I have never used python with anaconda, wouldn't be so sure why default `print()` statements don't work in them.
